# ----------- CONFIGURABLE START -----------
title:            "cccheng.net"
description:      ""
url:              https://cccheng.net # Site url, without a slash at the end.
signoff:          "cccheng" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         About
    url:          /about
    external:     false
  - name:         Github
    url:          https://github.com/cccheng
    external:     true
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"

plugins_dir:
  - jekyll-feed
